pos = input()
coast = int(input())
weght = int(input())
cash = int(input())
print(f'Чек\n{pos} - {weght}кг - {coast}руб/кг')
print(f'Итого: {weght * coast}руб')
print(f'Внесено: {cash}руб')
print(f'Сдача: {cash - weght * coast}')